const GETENTRY = "GETENTRYURL"
const RESTAURANTS = "RESTAURANTSURL"
const HOME_PAGE_GUESS = "HOME_PAGE_GUESS"
const HOME_PAGE_HOT = "HOME_PAGE_HOT"
const HOME_PAGE_GROUP = "HOME_PAGE_GROUP"
const NEARBYMERCHANT = "NEARBYMERCHANT"
export {
    GETENTRY,
    RESTAURANTS,
    HOME_PAGE_GUESS,
    HOME_PAGE_HOT,
    HOME_PAGE_GROUP,
    NEARBYMERCHANT
}
