const GETENTRY = "GETENTRYURL"
const RESTAURANTS = "RESTAURANTSURL"
const HOME_PAGE_GUESS = "HOME_PAGE_GUESS"
const HOME_PAGE_HOT = "HOME_PAGE_HOT"
const HOME_PAGE_GROUP = "HOME_PAGE_GROUP"
const CITY_SEARCH_MESSAGE = "CITY_SEARCH_MESSAGE"
const CITY_SEARCH_Address = "CITY_SEARCH_Address"



export {
    GETENTRY,
    RESTAURANTS,
    HOME_PAGE_GUESS,
    HOME_PAGE_HOT,
    HOME_PAGE_GROUP,
    CITY_SEARCH_MESSAGE,
    CITY_SEARCH_Address
}
